jobs:
- job: 'Build'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: |
      python -m pip install PyYAML argparse rospkg vcstools catkin_pkg python-dateutil rosdistro
      python -m pip install nose coverage flake8 mock codecov
  - script: |
      python -m nose --with-xunit test
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/*.xml'